### ISSUE TITLE
Il player pasquale usa chiaramente hack

### ISSUE THREAD

**Issue by DragonbornCommunity** [DragonbornCommunity/Minecraft#121]
Submitter: GianfraYT
Email: gianfrancofiletti7@gmail.com
Salve, sono qui per reportare il player pasquale, nel vostro server prison, facevamo pvp e da destra arriva a sinistra della pvpmine, mi da più hit del massimo, bow aimbot chiarissimo, mi colpisce attraverso blocchi, e inoltre quando mangiava le mele op continuava ad hittarmi.
Chiedo un controllo hack al più presto al player: pasquale.
Grazie mille

**Comment by TMHita** [comment]
Hai screenshot o altri tipi di prova?

**Comment by DragonbornCommunity** [comment]
In attesa di qualche prova

**Comment by DragonbornCommunity** [comment]
Niente prove per più di 11 giorni, richiesta negata.
