### ISSUE TITLE
[BUG] richiesta sban

### ISSUE THREAD

**Issue by DragonbornCommunity** [DragonbornCommunity/Minecraft#131]
Submitter: jeykflow
Email: jeykflowofficial@gmail.com
stavo giocando sul server towny, nella town firegard quando mi crasha il server, ci provo a rientrare e mi dice ban permanente motivo connession lost sinceramente pensavo era un bug di connessione ma aprendo il prompt sei comandi mi dice che non ho piu accesso a questo sevrer come faccio 
nick: jeykflow
server: towny

**Comment by TMHita** [comment]
Sei stato bannato per fly
