### ISSUE TITLE
REPORT

### ISSUE THREAD

**Issue by DragonbornCommunity** [DragonbornCommunity/Minecraft#134]
Submitter: Roamingo Ale2000
Email: florom7173@yahoo.it
Stavo con uno,io gli dico che me ne dovevo andare e mi da un colpo 2 sec prima che me ne andassi.Cosa succede?Rientro e sono morto.Tutta la robba in diamante sprecata perchè un nabbo di 10 anni ti da un colpo.Incazzato ho chiesto ad un helper l'aiuto.(Ale2000).Lui ha detto :''sisi ci penso io!''- mi ha detto di venire in arena dove c'era Roamingo(quello che mi ha fregato la robba).Io avevo l'armo in diamante e la spada.Ale2000 inizia ad attacarlo e io scendo.Cosa fa ale?Attacca me.2vs1.Robba perduta.

Ecco,è quello che è successo.

Nome nel server:Dragonborn: xXRetlawXX.

Io rivolevo soltanto la mia robba indietro..

Contatto skype: Edoard9451

Spero di essere aiutato..

**Comment by Strykex** [comment]
xXRetlawXX, leggi i cartelli prima di entrare in arena.
