### ISSUE TITLE
[HELP] NON RIESCO AD ACCEDERE AL SERVER, MI SONO DIMENTICATO LA PASSWORD!

### ISSUE THREAD

**Issue by DragonbornCommunity** [DragonbornCommunity/Minecraft#145]
Submitter: TheNikolay97
Email: matteo152@live.it
Salve, questa sera ho provato a fare l'accesso al server, sono Thenikolay97, e già da tempo giocavo su questo server.
Sfortunatamente non ricordo la vecchia password! Qualcuno può darmi una mano? Grazie mille!

**Comment by TMHita** [comment]
Se sei premium (hai comprato minecraft) manda un messaggio privato a Portanna su minecraft Italia dicendo che sei tu.  

Se invece sei Sp (quindi NON hai comprato minecraft)  prova a cambiare nome.
