### ISSUE TITLE
Bug kit start

### ISSUE THREAD

**Issue by DragonbornCommunity** [DragonbornCommunity/Minecraft#146]
Submitter: Lith97
Email: farafari97@yahoo.it
Nella modalità towny non hanno dato il kit start, sta cosa pensavo che era inizialmente colpa mia e che magari ero morto perdendo tutto, invece il giorno successivo altri player non si sono ritrovati il kit start. Forse c'è un problema con essential, chiedo gentilmente di controllare l'accaduto. Grazie.

**Comment by TMHita** [comment]
Il kit start continene  due pezzi di carne, uno stick, una spada di pietra e un cappello e scarpe in pelle
