### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by DragonbornCommunity** [DragonbornCommunity/Minecraft#158]
Submitter: Alex Serra
Email: lilliserra2009@hotmail.it
stavo giocando tranquilamente in casa mia poi dopo mezz?oretta vado ad aprire l'inventario del mio per ed era vuoto il pet prima aveva l'inventario pieno la skilltree Utility ed era di liv 45 o perso un intera armor diamond op un piccone eff10 ind 5 fortuna 5 un arco op infinity 10 fiamma potemza 10 impatto 5 4 mele op 56 blocchi di diamond sono le cose piu importanti il resto non lo ricordo

**Comment by TMHita** [comment]
Hai qualche prova valida? (Quando il per muore il suo inventario viene droppato a terra)
