### ISSUE TITLE
RUBATO ACCOUNT!!

### ISSUE THREAD

**Issue by DragonbornCommunity** [DragonbornCommunity/Minecraft#174]
Submitter: UndeRDoS
Email: tyeoutsideryebread4@gmail.com
Salve, Premetto che non sono registrato al server o almeno non io, qualche simpaticone ha usato il mio nickname (premium) per entrare in questo server, io vorrei tanto entrare, ma qualcuno ha usato il mio nickname. Potete aiutarmi?.
Grazie in anticipo.
Cordiali Saluti.

**Comment by TMHita** [comment]
Se sei premium manda un messaggio privato a Portanna su minecraft Italia dicendo che sei tu e la password verrà resettata consentendoti l'accesso
