### ISSUE TITLE
[SBAN] Possiedere cheat

### ISSUE THREAD

**Issue by DragonbornCommunity** [DragonbornCommunity/Minecraft#55]
Submitter: WhiteBull
Nickname: WhiteBull
Server: Vanilla
Premetto che sono già stato bannato una volta nel dal mod Minor_Miner per hack, ma subito dopo mi ha pulito il .minecraft e mi ha sbannato.
Oggi (21) mi ricontrolla , e io ho degli hacked client, che uso su altri server,  MA NON SU DRAGONBORN!
Sono stato permabannato  per NON aver utilizzato hack, ma per averle...
Non so da quale punto di vista voi la vediate , ma oltre a questo io vedevo solo helper "indecenti" (Non controllavano,non aiutavano etc.)
e quindi mi son proposto. Di certo una persona razionale se vuole proporsi helper non si mette a cheattare! Ma questo è un fatto di parola, 
quel che posso dirvi per certo è che non ho usato più hack dal primo ban, perchè come ben so , il secondo Unban si paga ...
Spero di aver spiegato bene perchè " Uso hack e vengo bannato , NON uso hack e vengo bannato" come faccio a giocare in santa pace?
Ci son rimasto male...

**Comment by TMHita** [comment]
Ma io la seconda volta l'ho bannato, perchè praticamente gli feci un controllo, ma non trovai hack. Poi ale2000 mi venne a dire che in chat aveva scritto cose tipo "Hahahah Minor_Miner non ha trovato un cazzo" e quindi, gli feci un altro controllo, poi ho visto la cartella della hack "wurst" tra l'altro era 1.9.. Quindi, poteva rientrare in qualsiasi momento con le hack. 

-Minor_Miner

**Comment by WhiteBullest** [comment]
Non è vero,questa cosa del "Ahahahahah minor non hai trovato nulla" non è assolutamente vera, è inventata.

**Comment by WhiteBullest** [comment]
Ale credeva lui stesso che io usassi cheat.In PVP , per questo si sarà inventato qualcosa, poi 2 giorni fa gli ho dimostrato di essere "molto forte" in confronto a lui . E ha capito che NON LI USAVO.
Lui mi segnalava perchè a un player di nome XxMatteoxX gli ho tolto mezza vita con un colpo . 
Quel colpo era una critical di Ascia
