### ISSUE TITLE
[AIUTO] [HACK]  zx6

### ISSUE THREAD

**Issue by DragonbornCommunity** [DragonbornCommunity/Minecraft#68]
Submitter: TMHita  
Email: tmhita@gmail.com
Il player di nome: "zx6" si finge staff/founder  e (in seguito) finge un riavvio del server mandando tutti all'hub. 
Ecco delle screenshot:

http://imgur.com/a/Y0SBL

Nome (mio): TMHita 
Nome (tizio): zx6
Server: Faction 
Mondo: ///

**Comment by TMHita** [comment]
PS Sbagliato il titolo, non è una segnalazione per hack.

**Comment by DragonbornCommunity** [comment]
Bannato

**Comment by lorenzo98747** [comment]
sono zx6.
io stavo scherzando,e comunque c'erano altre persone alla lobby che lo facevano.

**Comment by lorenzo98747** [comment]
[SBAN]
per favore sbannatemi
