### ISSUE TITLE
[Bug] Login

### ISSUE THREAD

**Issue by DragonbornCommunity** [DragonbornCommunity/Minecraft#77]
Submitter: Drarielk
Email: drarielk@hotmail.it
Salve, attualmente non riesco a fare il login nell'hub, in quanto mi da la PW errata nonostante inserisca quella corretta (ho fatto vari tentativi per esserne sicuro). Il problema è iniziato il 24/03 dopo le 21:00. Sucessivamente ho riprovato senza sucesso. Avendo poi visualizzato il forum, ho visto il messaggio che diceva di richiedere assistenza in TS, solo che mi han detto che c'è bisogno di un founder, motivo per cui lascio la segnalazione qui.

Grazie per l'attenzione

Drarielk

**Comment by Drarielk** [comment]
Mi sono fatto resettare la PW, questa segnalazione non è più necessaria.
