### ISSUE TITLE
[AIUTO] Non riesco ad effettuare login

### ISSUE THREAD

**Issue by DragonbornCommunity** [DragonbornCommunity/Minecraft#83]
Submitter: Arronax
Email: zipippo.1506@gmail.com
Buongiorno,
E' da oggi che con il mio account (Arronax) non riesco ad accedere al server, mi dice che non sono registrato. Non mi pare di essere stato bannato (non saprei nemmeno quale potrebbe essere il motivo anche fosse) o comunque in caso fosse successo non ero online. Grazie per l'aiuto

Cordialmente

Filippo Avogaro ovvero Arronax

**Comment by Arronax01** [comment]
Scusate sono sempre Arronax, problema risolto, bastava semplicemente registrarsi nuovamente (anche se non ne ho capito il motivo) comunque potete chiudere.
